import {
  CalendarCheckIcon,
  CalendarClockIcon,
  ClockAlertIcon,
  UserCheckIcon,
  UserPlusIcon,
  UsersIcon,
  UserXIcon,
} from "lucide-react"

export const dashboardStats = [
  {
    label: "Total Employees",
    value: 124,
    icon: UsersIcon,
    tone: "default" as const,
    subtext: "4 departments",
  },
  {
    label: "Present Today",
    value: 108,
    icon: UserCheckIcon,
    tone: "success" as const,
    trend: { value: "2.4%", direction: "up" as const },
    subtext: "87.1% turnout",
  },
  {
    label: "Late Arrivals",
    value: 12,
    icon: ClockAlertIcon,
    tone: "warning" as const,
    subtext: "Avg delay 14m",
  },
  {
    label: "Absent",
    value: 4,
    icon: UserXIcon,
    tone: "danger" as const,
    subtext: "2 unexcused",
  },
  {
    label: "On Leave",
    value: 8,
    icon: CalendarClockIcon,
    tone: "default" as const,
    subtext: "6 scheduled",
  },
]

export const attendanceBreakdown = [
  {
    label: "Present",
    value: 108,
    percentage: "87.1%",
    barClassName: "bg-emerald-600",
    textClassName: "text-emerald-700 dark:text-emerald-400",
    bgLight: "bg-emerald-50 text-emerald-800 border-emerald-200/60 dark:bg-emerald-950/40 dark:text-emerald-300",
  },
  {
    label: "Late",
    value: 12,
    percentage: "9.7%",
    barClassName: "bg-amber-500",
    textClassName: "text-amber-700 dark:text-amber-400",
    bgLight: "bg-amber-50 text-amber-800 border-amber-200/60 dark:bg-amber-950/40 dark:text-amber-300",
  },
  {
    label: "Absent",
    value: 4,
    percentage: "3.2%",
    barClassName: "bg-rose-500",
    textClassName: "text-rose-700 dark:text-rose-400",
    bgLight: "bg-rose-50 text-rose-800 border-rose-200/60 dark:bg-rose-950/40 dark:text-rose-300",
  },
  {
    label: "On Leave",
    value: 8,
    percentage: "6.5%",
    barClassName: "bg-blue-500",
    textClassName: "text-blue-700 dark:text-blue-400",
    bgLight: "bg-blue-50 text-blue-800 border-blue-200/60 dark:bg-blue-950/40 dark:text-blue-300",
  },
]

export const todaysActivity = [
  {
    id: "1",
    name: "Sarah Chen",
    initials: "SC",
    role: "Staff Frontend Eng",
    department: "Engineering",
    action: "Checked in",
    time: "8:57 AM",
    status: "on-time",
  },
  {
    id: "2",
    name: "David Kim",
    initials: "DK",
    role: "Senior Product Designer",
    department: "Product",
    action: "Checked in late",
    time: "9:14 AM",
    status: "late",
    delay: "+14m",
  },
  {
    id: "3",
    name: "Priya Patel",
    initials: "PP",
    role: "People Ops Lead",
    department: "People Ops",
    action: "On annual leave",
    time: "Day 1 of 4",
    status: "leave",
  },
  {
    id: "4",
    name: "Marcus Reid",
    initials: "MR",
    role: "DevOps Architect",
    department: "Infrastructure",
    action: "Checked out",
    time: "6:02 PM",
    status: "out",
    duration: "8h 15m logged",
  },
  {
    id: "5",
    name: "Elena Novak",
    initials: "EN",
    role: "Financial Analyst",
    department: "Finance",
    action: "Checked in",
    time: "8:44 AM",
    status: "on-time",
  },
]

export const pendingLeaveRequests = [
  {
    id: "1",
    name: "Priya Patel",
    initials: "PP",
    role: "People Ops Lead",
    department: "People & Culture",
    type: "Annual leave",
    duration: "4 days",
    dates: "Sep 12 – Sep 15",
    reason: "Pre-planned quarterly family leave",
  },
  {
    id: "2",
    name: "Marcus Reid",
    initials: "MR",
    role: "DevOps Architect",
    department: "Infrastructure",
    type: "Medical leave",
    duration: "1 day",
    dates: "Sep 10",
    reason: "Doctor appointment and recovery",
  },
  {
    id: "3",
    name: "Elena Novak",
    initials: "EN",
    role: "Financial Analyst",
    department: "Finance",
    type: "Personal leave",
    duration: "2 days",
    dates: "Sep 18 – Sep 19",
    reason: "Family event travel",
  },
]

export const taskOverview = [
  {
    label: "To do",
    value: 18,
    total: 84,
    barClassName: "bg-zinc-300 dark:bg-zinc-700",
    badge: "4 high priority",
  },
  {
    label: "In progress",
    value: 24,
    total: 84,
    barClassName: "bg-zinc-900 dark:bg-zinc-100",
    badge: "Sprint 18 deliverable",
  },
  {
    label: "Completed",
    value: 42,
    total: 84,
    barClassName: "bg-emerald-600",
    badge: "50% overall completion",
  },
]

export const recentActivity = [
  {
    id: "1",
    icon: UserPlusIcon,
    title: "New employee David Kim joined Product Design",
    subtitle: "Workstation and access credentials issued",
    timestamp: "2 hours ago",
    tone: "default" as const,
  },
  {
    id: "2",
    icon: CalendarCheckIcon,
    title: "Leave request approved for Sarah Chen",
    subtitle: "Annual leave: Sep 14 – Sep 16 (3 days)",
    timestamp: "3 hours ago",
    tone: "success" as const,
  },
  {
    id: "3",
    icon: ClockAlertIcon,
    title: "Attendance flagged: 3 employees marked late",
    subtitle: "Engineering department average arrival 9:20 AM",
    timestamp: "5 hours ago",
    tone: "warning" as const,
  },
  {
    id: "4",
    icon: UserCheckIcon,
    title: "Payroll draft generated for September",
    subtitle: "124 active employee payroll profiles verified",
    timestamp: "Yesterday, 4:30 PM",
    tone: "default" as const,
  },
]
