export type StatusTone = "success" | "warning" | "danger" | "info" | "neutral"

export const STATUS_TONE_MAP: Record<string, StatusTone> = {
  active: "success",
  present: "success",
  working: "success",
  completed: "success",
  approved: "success",
  connected: "success",
  "checked in": "success",
  "checked out": "info",
  late: "warning",
  pending: "warning",
  "in review": "warning",
  absent: "danger",
  rejected: "danger",
  overdue: "danger",
  disconnected: "danger",
  inactive: "neutral",
  draft: "neutral",
  "on leave": "info",
  onboarding: "info",
  probation: "warning",
  terminated: "danger",
}
