import type {
  Compensation,
  CompensationHistory,
  EmergencyContact,
  EmployeeActivity,
  EmployeeDocument,
  EmployeeNote,
  EmployeePersonalInfo,
  EmploymentDetails,
  PaymentInformation,
} from "@/types/employee-profile"

export const INITIAL_PERSONAL_INFOS: Record<string, EmployeePersonalInfo> = {
  emp_01: {
    preferredName: "Sarah",
    dateOfBirth: "1989-04-18",
    gender: "female",
    personalEmail: "sarah.chen.personal@gmail.com",
    alternatePhone: "+1 (555) 321-4567",
    addressLine: "742 Evergreen Terrace, Apt 4B",
    city: "New York",
    stateProvince: "NY",
    postalCode: "10001",
    country: "United States",
  },
  emp_02: {
    preferredName: "Rahim",
    dateOfBirth: "1991-08-24",
    gender: "male",
    personalEmail: "rahim.ahmed.dev@gmail.com",
    alternatePhone: "+1 (555) 789-0123",
    addressLine: "128 Innovation Way, Suite 12",
    city: "Jersey City",
    stateProvince: "NJ",
    postalCode: "07302",
    country: "United States",
  },
  emp_03: {
    preferredName: "David",
    dateOfBirth: "1995-11-12",
    gender: "male",
    personalEmail: "david.kim.tech@outlook.com",
    alternatePhone: "+1 (555) 654-9870",
    addressLine: "450 Broadway Ave, Apt 3A",
    city: "Brooklyn",
    stateProvince: "NY",
    postalCode: "11211",
    country: "United States",
  },
  emp_04: {
    preferredName: "Hasan",
    dateOfBirth: "1998-02-14",
    gender: "male",
    personalEmail: "hasan.khan.personal@yahoo.com",
    addressLine: "89 Queens Blvd, Suite 201",
    city: "Queens",
    stateProvince: "NY",
    postalCode: "11375",
    country: "United States",
  },
  emp_05: {
    preferredName: "Aiko",
    dateOfBirth: "1994-06-30",
    gender: "female",
    personalEmail: "aiko.tanaka.frontend@gmail.com",
    alternatePhone: "+1 (555) 432-8765",
    addressLine: "15 Central Park West, Apt 8D",
    city: "New York",
    stateProvince: "NY",
    postalCode: "10023",
    country: "United States",
  },
  emp_07: {
    preferredName: "Priya",
    dateOfBirth: "1990-09-15",
    gender: "female",
    personalEmail: "priya.patel.design@gmail.com",
    addressLine: "200 Mercer St, Apt 5F",
    city: "New York",
    stateProvince: "NY",
    postalCode: "10012",
    country: "United States",
  },
}

export const INITIAL_EMERGENCY_CONTACTS: Record<string, EmergencyContact[]> = {
  emp_01: [
    {
      id: "emg_01_1",
      name: "Michael Chen",
      relationship: "Spouse",
      phone: "+1 (555) 987-6543",
      email: "m.chen@outlook.com",
      address: "742 Evergreen Terrace, Apt 4B, New York, NY",
      isPrimary: true,
    },
  ],
  emp_02: [
    {
      id: "emg_02_1",
      name: "Nusrat Ahmed",
      relationship: "Spouse",
      phone: "+1 (555) 234-9876",
      alternatePhone: "+1 (555) 876-5432",
      email: "nusrat.ahmed@gmail.com",
      address: "128 Innovation Way, Suite 12, Jersey City, NJ",
      isPrimary: true,
    },
    {
      id: "emg_02_2",
      name: "Tariq Ahmed",
      relationship: "Brother",
      phone: "+1 (555) 345-6789",
      email: "tariq.ahmed@yahoo.com",
      isPrimary: false,
    },
  ],
  emp_03: [
    {
      id: "emg_03_1",
      name: "Grace Kim",
      relationship: "Mother",
      phone: "+1 (555) 890-1234",
      email: "grace.kim@gmail.com",
      isPrimary: true,
    },
  ],
  emp_05: [
    {
      id: "emg_05_1",
      name: "Kenji Tanaka",
      relationship: "Father",
      phone: "+1 (555) 567-8901",
      isPrimary: true,
    },
  ],
}

export const INITIAL_EMPLOYMENT_DETAILS: Record<string, EmploymentDetails> = {
  emp_01: {
    probationEndDate: "2024-06-15",
    confirmationDate: "2024-06-15",
    noticePeriod: "90 Days",
    workLocation: "HQ - New York Office",
    contractType: "permanent",
  },
  emp_02: {
    probationEndDate: "2024-08-01",
    confirmationDate: "2024-08-01",
    noticePeriod: "60 Days",
    workLocation: "HQ - New York Office",
    contractType: "permanent",
  },
  emp_03: {
    probationEndDate: "2026-10-15",
    noticePeriod: "30 Days",
    workLocation: "Hybrid (HQ / Remote)",
    contractType: "probationary",
  },
  emp_04: {
    probationEndDate: "2026-11-01",
    noticePeriod: "30 Days",
    workLocation: "Remote (US East)",
    contractType: "probationary",
  },
  emp_05: {
    probationEndDate: "2024-11-01",
    confirmationDate: "2024-11-01",
    noticePeriod: "30 Days",
    workLocation: "HQ - New York Office",
    contractType: "permanent",
  },
  emp_07: {
    probationEndDate: "2024-09-01",
    confirmationDate: "2024-09-01",
    noticePeriod: "60 Days",
    workLocation: "HQ - New York Office",
    contractType: "permanent",
  },
}

export const INITIAL_COMPENSATIONS: Record<string, Compensation> = {
  emp_01: {
    salaryType: "monthly",
    basicSalary: 11000,
    allowances: [
      { id: "alw_01", name: "Executive Allowance", amount: 1500 },
      { id: "alw_02", name: "Wellness & Tech", amount: 500 },
    ],
    effectiveDate: "2026-01-01",
    paymentCurrency: "USD ($)",
    notes: "Executive VP compensation structure with annual board performance bonus.",
  },
  emp_02: {
    salaryType: "monthly",
    basicSalary: 72000,
    allowances: [
      { id: "alw_11", name: "Housing Allowance", amount: 8000 },
      { id: "alw_12", name: "Transport Allowance", amount: 5000 },
    ],
    effectiveDate: "2026-09-01",
    paymentCurrency: "BDT (৳)",
    notes: "Engineering Manager band approved during Q3 organizational review.",
  },
  emp_03: {
    salaryType: "monthly",
    basicSalary: 6200,
    allowances: [
      { id: "alw_21", name: "Remote Work Stipend", amount: 350 },
    ],
    effectiveDate: "2026-07-15",
    paymentCurrency: "USD ($)",
    notes: "Probationary compensation package. Scheduled for review after 90 days.",
  },
  emp_05: {
    salaryType: "monthly",
    basicSalary: 6500,
    allowances: [
      { id: "alw_31", name: "Tech Allowance", amount: 300 },
      { id: "alw_32", name: "Commuter Transit", amount: 200 },
    ],
    effectiveDate: "2025-08-01",
    paymentCurrency: "USD ($)",
    notes: "Senior Frontend Developer package.",
  },
  emp_07: {
    salaryType: "monthly",
    basicSalary: 8500,
    allowances: [
      { id: "alw_41", name: "Design Leadership Stipend", amount: 800 },
    ],
    effectiveDate: "2025-06-01",
    paymentCurrency: "USD ($)",
    notes: "Head of Product compensation band.",
  },
}

export const INITIAL_COMPENSATION_HISTORIES: Record<string, CompensationHistory[]> = {
  emp_01: [
    {
      id: "ch_01_2",
      effectiveDate: "2026-01-01",
      salaryType: "monthly",
      basicSalary: 11000,
      allowances: [
        { id: "alw_01", name: "Executive Allowance", amount: 1500 },
        { id: "alw_02", name: "Wellness & Tech", amount: 500 },
      ],
      currency: "USD ($)",
      reason: "Annual Leadership Merit Adjustment",
      changedBy: "Amara Whitfield (Admin)",
      createdAt: "2026-01-02T10:00:00.000Z",
    },
    {
      id: "ch_01_1",
      effectiveDate: "2024-03-15",
      salaryType: "monthly",
      basicSalary: 9500,
      allowances: [
        { id: "alw_01_orig", name: "Executive Allowance", amount: 1000 },
      ],
      currency: "USD ($)",
      reason: "Initial Employment Agreement",
      changedBy: "Amara Whitfield (Admin)",
      createdAt: "2024-03-15T09:00:00.000Z",
    },
  ],
  emp_02: [
    {
      id: "ch_02_2",
      effectiveDate: "2026-09-01",
      salaryType: "monthly",
      basicSalary: 72000,
      allowances: [
        { id: "alw_11", name: "Housing Allowance", amount: 8000 },
        { id: "alw_12", name: "Transport Allowance", amount: 5000 },
      ],
      currency: "BDT (৳)",
      reason: "Promotion to Engineering Manager & Team Lead",
      changedBy: "Amara Whitfield (Admin)",
      createdAt: "2026-08-28T14:30:00.000Z",
    },
    {
      id: "ch_02_1",
      effectiveDate: "2024-05-01",
      salaryType: "monthly",
      basicSalary: 58000,
      allowances: [
        { id: "alw_11_orig", name: "Housing Allowance", amount: 6000 },
      ],
      currency: "BDT (৳)",
      reason: "Initial Senior Backend Developer Hire",
      changedBy: "Amara Whitfield (Admin)",
      createdAt: "2024-05-01T09:00:00.000Z",
    },
  ],
  emp_05: [
    {
      id: "ch_05_1",
      effectiveDate: "2024-08-01",
      salaryType: "monthly",
      basicSalary: 6500,
      allowances: [
        { id: "alw_31", name: "Tech Allowance", amount: 300 },
        { id: "alw_32", name: "Commuter Transit", amount: 200 },
      ],
      currency: "USD ($)",
      reason: "Initial Senior Frontend Hire",
      changedBy: "Amara Whitfield (Admin)",
      createdAt: "2024-08-01T09:00:00.000Z",
    },
  ],
}

export const INITIAL_PAYMENT_INFOS: Record<string, PaymentInformation> = {
  emp_01: {
    paymentMethod: "bank_transfer",
    bankName: "JPMorgan Chase Bank, N.A.",
    accountName: "Sarah Chen",
    accountNumber: "987654321098",
    branch: "Park Avenue Branch",
    routingNumber: "021000021",
    swiftCode: "CHASUS33XXX",
  },
  emp_02: {
    paymentMethod: "bank_transfer",
    bankName: "Eastern Bank PLC",
    accountName: "Rahim Ahmed",
    accountNumber: "104128009345",
    branch: "Gulshan Corporate Branch",
    routingNumber: "090271829",
    swiftCode: "EBLCBDDHXXX",
  },
  emp_03: {
    paymentMethod: "bank_transfer",
    bankName: "Bank of America, N.A.",
    accountName: "David Kim",
    accountNumber: "483920194820",
    branch: "Brooklyn Heights Branch",
    routingNumber: "026009593",
  },
  emp_05: {
    paymentMethod: "bank_transfer",
    bankName: "Citibank, N.A.",
    accountName: "Aiko Tanaka",
    accountNumber: "384910294821",
    branch: "Wall Street Branch",
    routingNumber: "021000089",
    swiftCode: "CITIUS33XXX",
  },
}

export const INITIAL_DOCUMENTS: Record<string, EmployeeDocument[]> = {
  emp_01: [
    {
      id: "doc_01_1",
      employeeId: "emp_01",
      name: "Executive Employment Agreement",
      category: "contract",
      fileName: "Sarah_Chen_Executive_Agreement.pdf",
      fileSize: "2.4 MB",
      fileType: "application/pdf",
      uploadedBy: "Amara Whitfield",
      uploadedDate: "2024-03-15",
      status: "verified",
    },
    {
      id: "doc_01_2",
      employeeId: "emp_01",
      name: "Official Offer Letter",
      category: "offer_letter",
      fileName: "Sarah_Chen_Offer_Signed.pdf",
      fileSize: "1.1 MB",
      fileType: "application/pdf",
      uploadedBy: "Amara Whitfield",
      uploadedDate: "2024-03-10",
      status: "verified",
    },
    {
      id: "doc_01_3",
      employeeId: "emp_01",
      name: "Passport Identification",
      category: "passport",
      fileName: "Passport_Scan_Confidential.pdf",
      fileSize: "850 KB",
      fileType: "application/pdf",
      uploadedBy: "Sarah Chen",
      uploadedDate: "2024-03-16",
      status: "verified",
    },
  ],
  emp_02: [
    {
      id: "doc_02_1",
      employeeId: "emp_02",
      name: "Employment Contract",
      category: "contract",
      fileName: "Rahim_Ahmed_Contract_2024.pdf",
      fileSize: "1.8 MB",
      fileType: "application/pdf",
      uploadedBy: "Amara Whitfield",
      uploadedDate: "2024-05-01",
      status: "verified",
    },
    {
      id: "doc_02_2",
      employeeId: "emp_02",
      name: "Offer Letter & Acceptance",
      category: "offer_letter",
      fileName: "Offer_Letter_Rahim_Ahmed.pdf",
      fileSize: "920 KB",
      fileType: "application/pdf",
      uploadedBy: "Amara Whitfield",
      uploadedDate: "2024-04-20",
      status: "verified",
    },
    {
      id: "doc_02_3",
      employeeId: "emp_02",
      name: "National Identification Card",
      category: "id_proof",
      fileName: "NID_Scan_Rahim_Ahmed.pdf",
      fileSize: "450 KB",
      fileType: "application/pdf",
      uploadedBy: "Rahim Ahmed",
      uploadedDate: "2024-05-03",
      status: "verified",
    },
  ],
  emp_03: [
    {
      id: "doc_03_1",
      employeeId: "emp_03",
      name: "Probationary Employment Agreement",
      category: "contract",
      fileName: "David_Kim_Probationary_Agreement.pdf",
      fileSize: "1.5 MB",
      fileType: "application/pdf",
      uploadedBy: "Amara Whitfield",
      uploadedDate: "2026-07-15",
      status: "pending",
    },
  ],
  emp_05: [
    {
      id: "doc_05_1",
      employeeId: "emp_05",
      name: "Permanent Employment Contract",
      category: "contract",
      fileName: "Aiko_Tanaka_Employment_Contract.pdf",
      fileSize: "1.9 MB",
      fileType: "application/pdf",
      uploadedBy: "Amara Whitfield",
      uploadedDate: "2024-08-01",
      status: "verified",
    },
  ],
}

export const INITIAL_NOTES: Record<string, EmployeeNote[]> = {
  emp_01: [
    {
      id: "note_01_1",
      employeeId: "emp_01",
      authorName: "Amara Whitfield",
      authorRole: "System Administrator",
      content: "Sarah is leading the Q4 engineering architectural overhaul. Excellent stakeholder communication and leadership.",
      createdAt: "2026-08-15T11:00:00.000Z",
      updatedAt: "2026-08-15T11:00:00.000Z",
    },
  ],
  emp_02: [
    {
      id: "note_02_1",
      employeeId: "emp_02",
      authorName: "Amara Whitfield",
      authorRole: "System Administrator",
      content: "Promotion to Engineering Manager confirmed by Executive team. Rahim successfully transitioned 3 junior developers into productive sprint contributors.",
      createdAt: "2026-08-28T14:30:00.000Z",
      updatedAt: "2026-08-28T14:30:00.000Z",
    },
    {
      id: "note_02_2",
      employeeId: "emp_02",
      authorName: "Sarah Chen",
      authorRole: "VP of Engineering",
      content: "Completed annual review with stellar performance scores in backend architecture and database scaling.",
      createdAt: "2026-09-02T16:00:00.000Z",
      updatedAt: "2026-09-02T16:00:00.000Z",
    },
  ],
  emp_03: [
    {
      id: "note_03_1",
      employeeId: "emp_03",
      authorName: "Rahim Ahmed",
      authorRole: "Engineering Manager",
      content: "David is currently in his 90-day evaluation period. Assigned to the API core refactoring task.",
      createdAt: "2026-08-01T10:15:00.000Z",
      updatedAt: "2026-08-01T10:15:00.000Z",
    },
  ],
  emp_04: [
    {
      id: "note_04_1",
      employeeId: "emp_04",
      authorName: "Amara Whitfield",
      authorRole: "System Administrator",
      content: "Account login access disabled pending HR policy review. Employee record preserved in probation status.",
      createdAt: "2026-09-01T09:00:00.000Z",
      updatedAt: "2026-09-01T09:00:00.000Z",
    },
  ],
}

export const INITIAL_ACTIVITIES: Record<string, EmployeeActivity[]> = {
  emp_01: [
    {
      id: "act_01_1",
      employeeId: "emp_01",
      type: "profile_updated",
      title: "Profile Information Updated",
      description: "Emergency contact details were verified and updated.",
      timestamp: "2026-09-05T14:20:00.000Z",
      actorName: "Sarah Chen",
      actorRole: "VP of Engineering",
    },
    {
      id: "act_01_2",
      employeeId: "emp_01",
      type: "account_created",
      title: "System Account Provisioned",
      description: "Administrator login account was provisioned with Executive role.",
      timestamp: "2024-03-15T09:00:00.000Z",
      actorName: "Amara Whitfield",
      actorRole: "System Administrator",
    },
  ],
  emp_02: [
    {
      id: "act_02_1",
      employeeId: "emp_02",
      type: "compensation_updated",
      title: "Compensation Band Revised",
      description: "Monthly basic salary revised to ৳72,000 with Housing & Transport allowances.",
      timestamp: "2026-09-01T10:00:00.000Z",
      actorName: "Amara Whitfield",
      actorRole: "System Administrator",
    },
    {
      id: "act_02_2",
      employeeId: "emp_02",
      type: "team_changed",
      title: "Team Leadership Assigned",
      description: "Appointed as Team Lead for Backend Engineering.",
      timestamp: "2026-08-28T14:30:00.000Z",
      actorName: "Sarah Chen",
      actorRole: "VP of Engineering",
    },
    {
      id: "act_02_3",
      employeeId: "emp_02",
      type: "document_uploaded",
      title: "Document Uploaded",
      description: "National Identification Card verified and stored.",
      timestamp: "2024-05-03T11:00:00.000Z",
      actorName: "Rahim Ahmed",
      actorRole: "Employee",
    },
    {
      id: "act_02_4",
      employeeId: "emp_02",
      type: "account_created",
      title: "Login Account Provisioned",
      description: "System credentials created with Manager access role.",
      timestamp: "2024-05-01T09:00:00.000Z",
      actorName: "Amara Whitfield",
      actorRole: "System Administrator",
    },
  ],
  emp_03: [
    {
      id: "act_03_1",
      employeeId: "emp_03",
      type: "password_changed",
      title: "First-Login Password Rotation Completed",
      description: "Employee rotated temporary password upon initial login.",
      timestamp: "2026-09-09T09:26:00.000Z",
      actorName: "David Kim",
      actorRole: "Employee",
    },
    {
      id: "act_03_2",
      employeeId: "emp_03",
      type: "account_created",
      title: "Login Account Provisioned",
      description: "Temporary password generated. Status set to Pending First Login.",
      timestamp: "2026-07-15T09:00:00.000Z",
      actorName: "Amara Whitfield",
      actorRole: "System Administrator",
    },
  ],
}
